<?php

namespace CadastroClienteBundle\Repository;

/**
 * CadastrooRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CadastrooRepository extends \Doctrine\ORM\EntityRepository
{
}
